// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEHRZmvYjgYACMJKf2GdIWNTuODYfvDTg',
    appId: '1:773558630446:web:1e990d32fe42bc8a2087bf',
    messagingSenderId: '773558630446',
    projectId: 'quizapp-2a054',
    authDomain: 'quizapp-2a054.firebaseapp.com',
    storageBucket: 'quizapp-2a054.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKDP5W6FFC3aZe8bB5Jnoss4p-fWCdaqs',
    appId: '1:773558630446:android:b03068e359250b4e2087bf',
    messagingSenderId: '773558630446',
    projectId: 'quizapp-2a054',
    storageBucket: 'quizapp-2a054.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1U5sOBelVyXdJzflRYQQ1_VFNY7sMmy0',
    appId: '1:773558630446:ios:183b498bc545c3682087bf',
    messagingSenderId: '773558630446',
    projectId: 'quizapp-2a054',
    storageBucket: 'quizapp-2a054.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1U5sOBelVyXdJzflRYQQ1_VFNY7sMmy0',
    appId: '1:773558630446:ios:183b498bc545c3682087bf',
    messagingSenderId: '773558630446',
    projectId: 'quizapp-2a054',
    storageBucket: 'quizapp-2a054.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEHRZmvYjgYACMJKf2GdIWNTuODYfvDTg',
    appId: '1:773558630446:web:635cf1c4819aeb7d2087bf',
    messagingSenderId: '773558630446',
    projectId: 'quizapp-2a054',
    authDomain: 'quizapp-2a054.firebaseapp.com',
    storageBucket: 'quizapp-2a054.firebasestorage.app',
  );
}
